### ISSUE TITLE
Specify dependencies

### ISSUE THREAD

**Issue by mweinelt** [Libera-Chat/ozone#3]
They are something along the lines of

- requests
- dnspython
- ftfy<6.0 (because https://github.com/rspeer/python-ftfy/commit/5af4582883a224f269109442ec858b708a834eff removes `ftfy.badness.text_cost`)

**Comment by ncoevoet** [comment]
text_cost isn't used anymore, you don't need to stay with ftfy < 6
Anyway, i guess we can take a look at import:
import os
import re
import sys
import time
import requests
from urllib.parse import urlencode
import sqlite3
import http.client
import threading
import dns.resolver
import dns.reversename
import json
import ipaddress
import random
