### ISSUE TITLE
error on operUp

### ISSUE THREAD

**Issue by ghost** [Libera-Chat/ozone#5]
Hi guys,

I got this error when the bot uses /oper

INFO 2022-03-14T18:50:45 OperUp: Opered up on pchat, sending user modes C
[18:51] <device> ERROR 2022-03-14T18:50:45 Server responded with unrequested ACK/NAK capabilities: req={'account-notify', 'server-time', 'away-notify', 'chghost', 'userhost-in-names', 'account-tag', 'extended-join', 'invite-notify', 'multi-prefix'}, ack={'account-notify', 'server-time', 'away-notify', 'chghost', 'userhost-in-names', 'account-tag', 'extended-join', 'solanum.chat/realhost', 'invite-notify', 'multi-prefix'}, nak=set()

Im using solanum ircd

thanks for the help.

**Comment by ncoevoet** [comment]
Hello

```
    def getIrc (self,irc):
        if not irc.network in self._ircs:
            self._ircs[irc.network] = Ircd(irc)
            self._ircs[irc.network].restore(self.getDb(irc.network))
            irc.requestCapabilities(["solanum.chat/realhost"])
```

add that line about requestCapabilities

**Comment by devicefix** [comment]
Hi,
thanks for replie can you give more info of where to put this, the file i mean.

thanks.

**Comment by ghost** [comment]
hello mate,

Where do i add this?

i add it in plugin.py but still get the same error.

**Comment by ncoevoet** [comment]
Which version of limnoria you are using ? 
because you need at least this commit on your version https://git.ptirc.org/Mirrors/Limnoria/commit/de277edb4275feb340ec2d6d0a5dd7a6e1057a6e

in plugin.py search for def getIrc, add the irc.requestCapabilities(["solanum.chat/realhost"]) as stated aboved
save, and restart the bot & plugin

**Comment by ghost** [comment]
thanks so much for the replie, after work i will try everything. Im using the last git.

**Comment by ncoevoet** [comment]
i'm closing this ticket as there is no feedback
